### ISSUE TITLE
Support image upload options

### ISSUE THREAD

**Issue by JasonBarnabe** [gera2ld/Stylish-oex#11]
http://userstyles.org/styles/76744/google-change-background-image

There's a (currently) hidden upload control here in the options section. This allows users to "upload" their own image into the style.

The trick to support this is to see if the install URL is longer than 2000 characters. If so, it should issue a POST instead. See this change for how it was done in Chrome:

https://github.com/JasonBarnabe/stylish/commit/2ec1d1218f2c4925b4e32c1df44464797e4da041

**Comment by gera2ld** [comment]
Fixed.
