### ISSUE TITLE
Update styles directly from userstyles.org

### ISSUE THREAD

**Issue by JasonBarnabe** [gera2ld/Stylish-oex#12]
Allow users to update their styles from userstyles.org if an update there exists. For styles with settings, always offer an update.

I just added support for this in Chrome and I included the server-side script updates for Chrome too. See the Stylish for Chrome update at https://github.com/JasonBarnabe/stylish/issues/87

**Comment by gera2ld** [comment]
I don't think this is a good way to check for updates.  
If a style is modified by the user, an update will be found. This may not be expected by the user.  
Why not just check by comparing version numbers or timestamps, just as the way userscripts add-ons work?

**Comment by JasonBarnabe** [comment]
In Firefox, I retain the original installed code and compare that to the code on userstyles.org. That way, a user updating a style on their own won't cause it to appear to require an update, but if the style is updated on userstyles.org after the user updates locally, it could still wipe out their changes.

**Comment by gera2ld** [comment]
So it works the same as version compare, and I think version compare is even simpler.
I am wondering why don't you just compare the timestamps of last update since there is a json file containing such data.

**Comment by JasonBarnabe** [comment]
The last update date is kind of ambiguous/undefined. Is it the last update of the code, or could it mean something like the name was updated. I don't think I decided on this, server-side.

One day, I hope that Chrome or Opera will support @document rules, then there will be no need to format it as JSON and it can be served as straight up CSS like in Firefox, with update checks just being downloading md5 hashes. This makes things simple and quick. Until then, I don't see what benefit relying on an additional piece of information will do. It's not like someone's going to "unupdate" a style, where the code will change but the version or date will go _down_, so why not just check the code?

**Comment by gera2ld** [comment]
Since you think a straight up CSS with `@document` rules is better to maintain, why not just support it in the addon? The original source code can be saved and parsed into sections every time after modification, so md5 hashes are available and `@document` rules are supported in a different way.
Actually Stylish for Opera supports Firefox CSS since the very first version.
However, Opera is going to use a webkit/blink core soon, and supports chromium extensions, so there is no need to develop a separate version for Opera any more.

**Comment by gera2ld** [comment]
[Opera Next](http://www.opera.com/next), version 15, which only supports chromium extensions, is coming. The extension files should be used by Opera in a development mode or packed into a `.nex` file with Opera.
I think you may submit a really official version for the brand new Opera. And this Stylish for Opera may serve for the old versions of Opera.

**Comment by JasonBarnabe** [comment]
Parsing CSS is a somewhat difficult task, and since I had already written it server-side (to support user scripts) I decided not to write another parser for the sake of Chrome.

Do you know of any documentation about how Opera will support Chrome extensions? 

You've done a good job with Stylish for Opera and if the current Chrome version will be the replacement, I would welcome anything you have to contribute to it.

**Comment by gera2ld** [comment]
[Here](http://dev.opera.com/extension-docs/) is the new documentation for building extensions for chromium-based Opera. It seems that the Stylish for Chrome works well on Opera Next without making any changes.

**Comment by LouCypher** [comment]
> version 15, which only supports chromium extensions, is coming.

It's just been [relased](http://business.opera.com/press/releases/desktop/2013-07-02) today.
