### ISSUE TITLE
Stylish-oex not detected by userstyles.org

### ISSUE THREAD

**Issue by jesus2099** [gera2ld/Stylish-oex#13]
I don’t know whether it’s [website](https://userstyles.org) or extension’s (1.5.2) fault.
`div#style-install-opera > div#style-install-opera-old` (_To use this style, install Stylish._) is shown in userstyles pages instead of `div#stylish-installed-style-not-installed` that allows install.
cf. https://forum.userstyles.org/discussion/comment/96602/#Comment_96602

**Comment by gera2ld** [comment]
In my case, when I go to https://userstyles.org directly, I get what you get.
But when I turn on a proxy such as VPN, everything works.
The CDN used by https://userstyles.org seems to be unreachable in some areas, which I cannot help with.

**Comment by jesus2099** [comment]
Thanks for your tests !
I hope it will get fixed over there. :)
