### ISSUE TITLE
Language fixes

### ISSUE THREAD

**Issue by JasonBarnabe** [gera2ld/Stylish-oex#4]
Regular-Expressions: -> Regular expressions:
Url-prefixes: -> URL prefixes:
Urls: -> URLs:
Get more styles from UserStyles.org -> Get more styles from userstyles.org
CSS List -> Installed Styles
Update -> Check for Updates
New CSS -> New Style
No update is found! -> No update found
Search styles for this site -> Find styles for this site

Remove (C) notice as you're GPL now :)

**Comment by JasonBarnabe** [comment]
Also, you don't need to specify "Stylish for Opera". Just "Stylish" is fine.

**Comment by gera2ld** [comment]
Fixed.
