### ISSUE TITLE
Style installed with Options window open show be reflected

### ISSUE THREAD

**Issue by JasonBarnabe** [gera2ld/Stylish-oex#7]
-Open Stylish Options window
-In another tab, install from userstyles.org

Options window does not reflect the new style until refresh.

**Comment by gera2ld** [comment]
Fixed. It is supposed that one options page is opened at once. So if several options pages are opened at the same time and a style is removed from one of them, nothing will change in others until refresh. I have not found a way to keep only one options page opened at once yet.
